# Generated by Django 4.0.5 on 2023-01-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_on',
            new_name='created',
        ),
    ]
